In [1]:
import numpy as np

# Quelques fonctions utiles - Solution 

On a créé un tableau 2D contenant des valeurs aléatoires. 

In [2]:
rdm_mat = np.random.randn(20, 20)
rdm_mat

array([[-4.72988358e-01, -4.85275192e-01,  2.30228608e+00,
        -1.41435665e+00, -7.65088422e-01,  6.38811633e-01,
        -9.34051128e-01, -1.65341723e+00, -6.96764338e-01,
        -2.73508717e-01, -3.35162303e-01, -7.57432198e-01,
         1.39226394e+00, -1.83132203e+00,  7.94699968e-01,
         9.54075203e-01,  1.82445740e+00,  5.49180501e-01,
         1.45079100e+00, -2.15162613e+00],
       [ 1.27176471e+00, -1.65093910e-01,  1.95256522e-01,
         8.28865519e-01,  1.48161261e+00,  7.17913888e-01,
         7.16596599e-01,  6.10673158e-01,  5.70009339e-01,
        -1.28935174e+00,  8.92870919e-01,  3.89740172e-01,
         1.40830141e+00, -5.40868237e-01, -9.01587164e-01,
        -1.27394073e-01, -3.33024219e-01,  5.94264589e-01,
        -2.14775756e-01, -8.07744365e-01],
       [-9.25150125e-01,  1.41006161e-01, -2.30822218e+00,
        -8.24688649e-01, -7.01514675e-01,  2.11360902e-01,
        -7.63996780e-01, -1.06922831e+00, -4.49623495e-01,
         4.02709055e-01,  3.4

Donner le type de la variable rdm_mat

In [3]:
type(rdm_mat)

numpy.ndarray

Donner la somme des éléments du tableau 2D

In [4]:
#np.sum(rdm_mat)
rdm_mat.sum()

-11.891889209417727

Faire en sorte de récupérer la valeur maximale sur chaque ligne (sans utiliser ni fonction ni boucle) 

In [5]:
np.max(rdm_mat, axis=1)

array([2.30228608, 1.48161261, 0.99343941, 1.18117566, 2.47512696,
       1.88889842, 1.06897287, 1.6765991 , 1.93841683, 1.66989676,
       1.43097802, 2.02629983, 1.78808176, 1.50641489, 1.61624325,
       1.38831493, 2.16710953, 3.04333294, 1.9743076 , 2.51659364])

Faire la même chose en définissant un tableau avec une boucle for et la fonction max de numpy

In [6]:
[np.max(rdm_mat[i]) for i in range(0,len(rdm_mat))]
#avec une fonction
def maxCol(array): 
    tab = []
    for i in range(0,len(array)):
        tab.append(np.max(array[i]))
    return tab 

Faire de même pour récupérer la valeur maximum pour chaque colonne (sans boucles)

In [7]:
np.max(rdm_mat, axis=0)

array([2.51659364, 1.93841683, 2.30228608, 1.77486421, 1.88889842,
       1.4775859 , 2.02629983, 1.51173255, 2.16710953, 0.86747494,
       1.2574294 , 1.9743076 , 1.40830141, 0.86841025, 1.18977206,
       1.78808176, 1.8244574 , 1.27075853, 1.6765991 , 3.04333294])

On crée un vecteur aléatoire de taille 1x100

In [8]:
rdm_vect = np.random.randn(100)
rdm_vect.shape

(100,)

Récupérer la position de la valeur maximale du vecteur avec la méthode np.argmax

In [9]:
np.argmax(rdm_vect)

16

In [10]:
rdm_vect

array([-0.67106473,  0.36215134, -1.05945356, -1.20340101,  0.49001208,
       -0.48860688, -1.4678811 ,  1.80381469,  0.39658892,  1.08475852,
        0.67929238,  0.03205926,  1.06714511, -0.59310659,  0.74901118,
       -0.59161898,  3.40414015, -1.98974613, -0.82336933,  0.4898189 ,
       -0.10858838,  1.42164915, -0.68889652, -0.1488928 , -0.80642588,
       -0.2833762 , -1.65818207,  0.56882504,  0.56394712, -0.6604258 ,
        0.30373784,  0.34248005, -0.92797496, -0.2438173 ,  1.52628732,
       -0.74196725, -0.11196987,  1.27036734, -0.54838284, -0.15490381,
       -0.67167549, -0.40018997, -0.3241609 , -2.07761055,  0.30036004,
        0.29855425,  0.30881895, -0.96584365,  0.39274468,  0.17416622,
        0.07458131,  0.98171624, -0.54431037,  0.85680062,  0.76824545,
       -0.76942172, -1.64993796,  0.62619757,  0.32362656, -0.19970366,
        2.23981504,  0.2792521 , -0.64986266, -0.12669426, -0.17088895,
       -0.03757205, -0.89895144, -0.94020167,  1.24672539,  0.77

Convertir le vecteur en un tableau 10, 10

In [11]:
new_vect = rdm_vect.reshape(10,10)
new_vect

array([[-0.67106473,  0.36215134, -1.05945356, -1.20340101,  0.49001208,
        -0.48860688, -1.4678811 ,  1.80381469,  0.39658892,  1.08475852],
       [ 0.67929238,  0.03205926,  1.06714511, -0.59310659,  0.74901118,
        -0.59161898,  3.40414015, -1.98974613, -0.82336933,  0.4898189 ],
       [-0.10858838,  1.42164915, -0.68889652, -0.1488928 , -0.80642588,
        -0.2833762 , -1.65818207,  0.56882504,  0.56394712, -0.6604258 ],
       [ 0.30373784,  0.34248005, -0.92797496, -0.2438173 ,  1.52628732,
        -0.74196725, -0.11196987,  1.27036734, -0.54838284, -0.15490381],
       [-0.67167549, -0.40018997, -0.3241609 , -2.07761055,  0.30036004,
         0.29855425,  0.30881895, -0.96584365,  0.39274468,  0.17416622],
       [ 0.07458131,  0.98171624, -0.54431037,  0.85680062,  0.76824545,
        -0.76942172, -1.64993796,  0.62619757,  0.32362656, -0.19970366],
       [ 2.23981504,  0.2792521 , -0.64986266, -0.12669426, -0.17088895,
        -0.03757205, -0.89895144, -0.94020167

Calculer la moyenne de chaque ligne de ce tableau (sans boucles)

In [12]:
np.mean(new_vect, axis=0)

array([ 0.28313337,  0.27791388, -0.07696555, -0.62259095,  0.24803792,
       -0.43100648, -0.05106513, -0.16046468,  0.15231288,  0.11262662])

Faire un tableau qui contient la moyenne de chaque colonne du tableau 

In [13]:
[ np.mean(new_vect[i]) for i in range(0,10) ]

[-0.07530817270010533,
 0.24236259667941756,
 -0.18003663373648612,
 0.07138565145344641,
 -0.29648364285870293,
 0.046779404164947025,
 0.17144842210684746,
 0.028220247832670676,
 -0.03620062767068015,
 -0.24023535363564577]

Calculer la somme de chaque colonne (sans boucles)

In [14]:
np.sum(new_vect, axis=1)

array([-0.75308173,  2.42362597, -1.80036634,  0.71385651, -2.96483643,
        0.46779404,  1.71448422,  0.28220248, -0.36200628, -2.40235354])

Calculer la somme cumulée pour chaque ligne (sans boucles)

In [15]:
np.sum(new_vect, axis=0)

array([ 2.83133375,  2.77913879, -0.76965548, -6.22590953,  2.48037925,
       -4.31006482, -0.5106513 , -1.60464676,  1.52312885,  1.12626618])

## Petits exercices - Solution 


In [16]:
Z = np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [18]:
Z = np.arange(50)
Z = Z[::-1]
Z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [19]:
Z = np.arange(9).reshape(3,3)
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
Z = np.eye(3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
Z = np.random.random((3,3,3))
Z

array([[[0.68398972, 0.45755268, 0.12681669],
        [0.76309979, 0.14363006, 0.48407329],
        [0.02198367, 0.31115525, 0.16519806]],

       [[0.43548155, 0.6880716 , 0.72130904],
        [0.89665789, 0.27271726, 0.64272984],
        [0.84757449, 0.25872878, 0.90741835]],

       [[0.22057449, 0.54860642, 0.25107795],
        [0.5350491 , 0.05957162, 0.210269  ],
        [0.93387449, 0.31999536, 0.8405817 ]]])

In [22]:
l = [0,1,2,3,4]
s = sum(l)
m = np.mean(l)
s, m 

(10, 2.0)

In [23]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)
#autre méthode 
equal = np.array_equal(A,B)
print(equal)

False
False


In [24]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
Z

array([[-0.57152366,  0.28344463, -1.13438776, -0.00597935, -0.92150968],
       [-0.82573245,  0.38177663,  0.19762945,  1.83093683,  0.04732477],
       [-0.38640739,  1.51995093,  1.61732433,  1.5807789 ,  0.64664843],
       [-1.18159893,  1.79296439, -0.19501173, -1.22393908, -1.12004044],
       [-0.06234616, -0.3731319 ,  0.33463404, -1.33547418, -0.89633059]])

In [25]:
A = np.array([[1, 2], [3, 4]])
print("la matrice A :\n {} \n\nla transposé de la matrice A :\n {}".format(A, A.transpose()))

la matrice A :
 [[1 2]
 [3 4]] 

la transposé de la matrice A :
 [[1 3]
 [2 4]]


In [26]:
n = 10
p = 1
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [27]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [28]:
A = np.array(([1,3,3],[1,4,3],[1,3,4]))
b = [1,2,3]
x = np.dot(np.linalg.inv(A), b)
x

array([-8.,  1.,  2.])